library(shinydashboard)
library(shinyWidgets)
library(shiny)

library(DT)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(wordcloud)
library(plotly)
library(tm)
library(forcats)
library(viridis)
library(RColorBrewer)

library(stringr)
library(bslib)
library(fontawesome)
library(kableExtra)
library(gridExtra)
library(tibble)
library(fBasics)
library(DescTools)
library(FinTS)
library(rugarch)
library(reshape2)